Add caching capabilities.

diff --git a/mkres b/mkres
--- a/mkres
+++ b/mkres
@@ -84,39 +84,61 @@ build() {
   echo "" > "$LATEX_BODY"
   for file in $(find "$TMPDIR" -name "$FILETITLE.*" -not -name "$FILETITLE.*.csv" | sort);
   	do
-  		title="$(pcregrep -Mo 'subsection\{\K((?s).)*?(?=\})' $file)"
-  		latex="$(pcregrep -Mo '<LATEX>\K((?s).)*?(?=</LATEX>)' $file)"
-  		alignment="$(pcregrep -Mo '<COLS>\K((?s).)*?(?=</COLS>)' $file)"
-  		csvfile="$(basename $file).csv"
-      if [[ ! $alignment =~ ^[Xlrc]+$ ]]; then
-        echo "Missing, bad or empty <COLS> tag for table \"$title\": \"$alignment\""
-        exit
-      fi
-      if [ -f "$TMPDIR/$csvfile" ]; then
-        # Do queries on second run
-        printf   " ---> \"$title\" ($alignment):: SQL"
-        MYSQL_PWD=$MYSQL_PASS mysql -h$MYSQL_HOST -u$MYSQL_USER < $file | sed 's/,/\\char44\{\}/g' | sed 's/_/\\char95\{\}/g' | sed 's/|/\\char124\{\}/g'| sed 's/%/\\char37\{\}/g'| sed 's/ /\\:/g' | sed 's/\t/,/g' | iconv -f ISO-8859-1 -t UTF-8 >> "$TMPDIR/$csvfile"
-        printf "\r ---> \"$title\" ($alignment):: OK!\n"
-      else
-        # Dry-run queries first
-        echo "Checking $title ($alignment)"
-        touch "$TMPDIR/$csvfile"
-        cat "$file" | tr "\n" "\f" | sed -e 's/\fSELECT/ EXPLAIN SELECT/g' | sed -e 's/UNION/;/g' | MYSQL_PWD=$MYSQL_PASS mysql -h$MYSQL_HOST -u$MYSQL_USER > /dev/null
-        if [ ${PIPESTATUS[4]} -eq 1 ]; then
+      MD5=($(md5sum "$file"))
+      CACHEDIR="/tmp/mkres_cache/$MD5"
+      CACHEFILE_LATEX="$CACHEDIR/$(basename $file)"
+      CACHEFILE_CSV="$CACHEFILE_LATEX.csv"
+      LATEX_BODY_TMP=$(mktemp)
+      CSVFILE="$(basename $file).csv"
+      title="$(pcregrep -Mo 'subsection\{\K((?s).)*?(?=\})' $file)"
+      alignment="$(pcregrep -Mo '<COLS>\K((?s).)*?(?=</COLS>)' $file)"
+      if [ ! -f "$CACHEFILE_CSV" ]; then
+    		latex="$(pcregrep -Mo '<LATEX>\K((?s).)*?(?=</LATEX>)' $file)"
+        latexBelow="$(pcregrep -Mo '<LATEX_BELOW>\K((?s).)*?(?=</LATEX_BELOW>)' $file)"
+        if [[ ! $alignment =~ ^[Xlrc]+$ ]]; then
+          echo "Missing, bad or empty <COLS> tag for table \"$title\": \"$alignment\""
           exit
         fi
+        if [ -f "$TMPDIR/$CSVFILE" ]; then
+          # Do queries on second run
+          printf   " ---> \"$title\" ($alignment):: SQL"
+          MYSQL_PWD=$MYSQL_PASS mysql -h$MYSQL_HOST -u$MYSQL_USER < $file | sed 's/,/\\char44\{\}/g' | sed 's/_/\\char95\{\}/g' | sed 's/|/\\char124\{\}/g'| sed 's/%/\\char37\{\}/g'| sed 's/ /\\:/g' | sed 's/\t/,/g' | iconv -f ISO-8859-1 -t UTF-8 >> "$TMPDIR/$CSVFILE"
+          printf "\r ---> \"$title\" ($alignment):: OK!\n"
+        else
+          # Dry-run queries first
+          cat "$file" | tr "\n" "\f" | sed -e 's/\fSELECT/ EXPLAIN SELECT/g' | sed -e 's/UNION/;/g' | MYSQL_PWD=$MYSQL_PASS mysql -h$MYSQL_HOST -u$MYSQL_USER > /dev/null
+          if [ ${PIPESTATUS[4]} -eq 1 ]; then
+            exit
+          fi
+        fi
+    		echo "\\begin{minipage}{\\textwidth}" >> "$LATEX_BODY_TMP"
+        echo "\\setlength{\\parskip}{\\baselineskip}" >> "$LATEX_BODY_TMP"
+    		echo "$latex" >> "$LATEX_BODY_TMP"
+    		echo "\\medskip\\FloatBarrier" >> "$LATEX_BODY_TMP"
+    		printf "\\pgfplotstabletypeset[begin table={\\\\begin{tabularx}{\\\\textwidth}{%s}}]{%s}\n" \
+    					 "$alignment" \
+    					 "$CSVFILE" \
+    					 >> "$LATEX_BODY_TMP"
+    		echo "\\FloatBarrier" >> "$LATEX_BODY_TMP"
+        echo "$latexBelow" >> "$LATEX_BODY_TMP"
+        echo "\\bigskip" >> "$LATEX_BODY_TMP"
+    		echo "\\end{minipage}" >> "$LATEX_BODY_TMP"
+    		echo "\\bigskip" >> "$LATEX_BODY_TMP"
+        cat "$LATEX_BODY_TMP" >> "$LATEX_BODY"
+        if [ -f "$TMPDIR/$CSVFILE" ]; then
+          mkdir -p "$CACHEDIR"
+          mv "$LATEX_BODY_TMP" "$CACHEFILE_LATEX"
+          cp "$TMPDIR/$CSVFILE" "$CACHEFILE_CSV"
+        else
+          touch "$TMPDIR/$CSVFILE"
+        fi
+      else
+        cat "$CACHEFILE_LATEX" >> "$LATEX_BODY"
+        if [ ! -f "$TMPDIR/$CSVFILE" ]; then
+          cp "$CACHEFILE_CSV" "$TMPDIR/$CSVFILE"
+          echo " ---> \"$title\" ($alignment):: OK! (Cached)"
+        fi
       fi
-  		echo "\\begin{minipage}{\\textwidth}" >> "$LATEX_BODY"
-      echo "\\setlength{\\parskip}{\\baselineskip}" >> "$LATEX_BODY"
-  		echo "$latex" >> "$LATEX_BODY"
-  		echo "\\medskip\\FloatBarrier" >> "$LATEX_BODY"
-  		printf "\\pgfplotstabletypeset[begin table={\\\\begin{tabularx}{\\\\textwidth}{%s}}]{%s}\n" \
-  					 "$alignment" \
-  					 "$csvfile" \
-  					 >> "$LATEX_BODY"
-  		echo "\\FloatBarrier" >> "$LATEX_BODY"
-  		echo "\\end{minipage}" >> "$LATEX_BODY"
-  		echo "\\bigskip" >> "$LATEX_BODY"
   done
   cd "$TMPDIR"
   pdflatex --halt-on-error "$LATEX_MAIN" > "$TMPDIR/pdflatex.log"
